### ISSUE TITLE
Add support for aggregate measurements

### ISSUE THREAD

**Issue by fronzbot** [fronzbot/minflux#33]
**minflux version (`minflux --version`):** 0.0.10

**Python release (`python3 --version`):** 3.5.3

###  Description of problem/request:
Some categories from mint are broken down into sub categories, but in some instances this extra information doesn't provide any value and the parent category would be more useful.  We should have a feature that allows category aggregation.

### Example configuration proposal:
```yaml
mint:
    ...
    groups:
        month: 1
        restaurants:
            - Restaurants
            - Fast Food
            - Alcohol & Bars
        hobbies:
            - Boardgames
            - Woodworking
```

This would create a `sum_restaurant_1m` measurement and `sum_hobbies_1m` measurement (named as such to prevent measurement name collisions) that are summed over 1 month (eventually support days as well, for example `days: 10` would sum over a ten day range and have a `sum_*_10d` measurement name)
